services:
  - type: web
    name: video-service
    env: docker
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
    disk:
      name: video-cache
      mountPath: /app/data
      sizeGB: 1

