from manim import *
class Introduction(Scene):
    def construct(self):
    title = Tex("Simple Math: An Animated Adventure!", color=BLACK).scale(1.2)
    title.move_to(UP * 2)
    self.add(title)
    mathy = SVGMobject("squirrel.svg")  # Replace with actual SVG file
    mathy.scale(0.8)
    background = Rectangle(width=config.frame_width, height=config.frame_height, color=WHITE, fill_opacity=1)
    self.add(background)
    numbers = VGroup(*[Text(str(i), color=BLUE) for i in range(10)])
    numbers.arrange(RIGHT)
    numbers.scale(0.5)
    numbers.move_to(DOWN * 2)
    shapes = VGroup(Circle(radius=0.3, color=RED), Square(side_length=0.3, color=GREEN), Triangle(color=YELLOW))
    shapes.arrange(RIGHT)
    shapes.scale(0.5)
    shapes.move_to(DOWN * 3)
    self.play(FadeIn(mathy), Write(title), Write(numbers), Write(shapes))
    self.wait(2)
    intro_text = Tex("Hi everyone! I'm Mathy, and I love math! ", color=BLACK)
    intro_text.move_to(UP * 0.5)
    self.play(Write(intro_text))
    adventure_text = Tex("Are you ready for an awesome adventure into the world of simple math? It's easier than you think!", color=BLACK)
    adventure_text.move_to(DOWN * 0)
    self.play(Write(adventure_text))
    topic_text = Tex("Today, we're going to explore adding, subtracting, and some super cool counting tricks!", color=BLACK)
    topic_text.move_to(DOWN * 0.5)
    self.play(Write(topic_text))
    self.wait(3)
    self.play(FadeOut(title, mathy, numbers, shapes, intro_text, adventure_text, topic_text))
    self.wait(1)
class AdditionScene(Scene):
    def construct(self):
    text = Tex("Let's start with Addition!", color=BLACK).scale(1.2)
    self.play(Write(text))
    self.wait(1)
    self.play(FadeOut(text))
    apple1 = Circle(radius=0.5, color=RED, fill_opacity=1).move_to(LEFT * 2)
    apple2 = Circle(radius=0.5, color=RED, fill_opacity=1).move_to(LEFT * 1)
    plus = MathTex("+", color=BLACK).scale(2).move_to(ORIGIN)
    apple3 = Circle(radius=0.5, color=RED, fill_opacity=1).move_to(RIGHT * 1)
    apple4 = Circle(radius=0.5, color=RED, fill_opacity=1).move_to(RIGHT * 2)
    equals = MathTex("=", color=BLACK).scale(2).move_to(RIGHT * 3)
    self.play(FadeIn(apple1, apple2))
    self.play(Write(plus))
    self.wait(0.5)
    self.play(FadeIn(apple3))
    self.play(FadeIn(apple4))
    self.play(Write(equals))
    equation = MathTex("2 + 2 = 4", color=BLACK).scale(1.5).move_to(DOWN * 2)
    self.play(Write(equation))
    self.wait(3)
    self.play(FadeOut(apple1, apple2, plus, apple3, apple4, equals, equation))
    self.wait(1)
class SubtractionScene(Scene):
    def construct(self):
    text = Tex("Now, Subtraction!", color=BLACK).scale(1.2)
    self.play(Write(text))
    self.wait(1)
    self.play(FadeOut(text))
    ball1 = Circle(radius=0.5, color=BLUE, fill_opacity=1).move_to(LEFT * 2)
    ball2 = Circle(radius=0.5, color=BLUE, fill_opacity=1).move_to(LEFT * 1)
    ball3 = Circle(radius=0.5, color=BLUE, fill_opacity=1).move_to(ORIGIN)
    minus = MathTex("-", color=BLACK).scale(2).move_to(RIGHT * 1)
    ball4_gone = Circle(radius=0.5, color=BLUE, fill_opacity=1).move_to(RIGHT * 2)
    equals = MathTex("=", color=BLACK).scale(2).move_to(RIGHT * 3)
    ball5 = Circle(radius=0.5, color=BLUE, fill_opacity=1).move_to(RIGHT * 4)
    ball6 = Circle(radius=0.5, color=BLUE, fill_opacity=1).move_to(RIGHT * 5)
    self.play(FadeIn(ball1, ball2, ball3))
    self.play(Write(minus))
    self.play(ball1.animate.fade(1))
    self.play(Write(equals))
    self.play(FadeIn(ball5, ball6))
    equation = MathTex("3 - 1 = 2", color=BLACK).scale(1.5).move_to(DOWN * 2)
    self.play(Write(equation))
    self.wait(3)
    self.play(FadeOut(ball1, ball2, ball3, minus, equals, ball5, ball6, equation, ball4_gone))
    self.wait(1)
class CountingScene(Scene):
    def construct(self):
    text = Tex("Let's Count!", color=BLACK).scale(1.2)
    self.play(Write(text))
    self.wait(1)
    self.play(FadeOut(text))
    stars = VGroup(*[Star(color=YELLOW, fill_opacity=1) for _ in range(5)])
    stars.arrange(RIGHT)
    for i, star in enumerate(stars):
    self.play(FadeIn(star))
    number = Text(str(i+1), color=BLACK).move_to(star.get_center() + DOWN*1)
    self.play(Write(number))
    self.wait(0.5)
    self.wait(2)
    self.play(FadeOut(*stars))
class Conclusion(Scene):
    def construct(self):
    text = Tex("Great job learning simple math!", color=BLACK).scale(1.2)
    self.play(Write(text))
    self.wait(2)
    summary = Tex("We learned addition, subtraction, and counting!", color=BLACK).move_to(DOWN * 1)
    self.play(Write(summary))
    self.wait(3)
class Main(Scene):
    def construct(self):
    self.add_sound("upbeat_music.mp3", loop=True)
    self.play(FadeIn(Rectangle(width=config.frame_width, height=config.frame_height, color=WHITE, fill_opacity=1)))
    self.next_section("Introduction")
    Introduction.construct(self)
    self.next_section("Addition")
    AdditionScene.construct(self)
    self.next_section("Subtraction")
    SubtractionScene.construct(self)
    self.next_section("Counting")
    CountingScene.construct(self)
    self.next_section("Conclusion")
    Conclusion.construct(self)
    self.stop_sound()